platform:ios,'8.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'UMengAnalytics-NO-IDFA'
pod 'RongCloudIMLib'
pod 'MJRefresh'
pod 'MWPhotoBrowser'
pod 'UMengSocial', '~> 4.2.3'
pod 'FMDB'
pod 'pop'
pod 'NSLogger'
pod 'AliyunOSSiOS'
pod 'JDStatusBarNotification'
pod 'RKNotificationHub'
pod 'SDAutoLayout'
pod 'YTKNetwork'
pod 'GVUserDefaults'
pod 'CTPersistance'
