platform:ios,'8.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'FMDB'
pod 'pop'
pod 'NSLogger'
pod 'JDStatusBarNotification'
pod 'RKNotificationHub'
pod 'SDAutoLayout'
pod 'YTKNetwork'
pod 'GVUserDefaults'
pod 'CTPersistance'
